# Generated by Django 4.2.16 on 2024-11-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                ("expiry_date", models.DateField()),
                ("purchase_date", models.DateField()),
                ("supplier", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
            ],
        ),
    ]
