# Generated by Django 4.2.16 on 2024-11-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restoapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Item",),
    ]
